# Generated by Django 4.2.7 on 2023-11-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0004_alter_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2023-11-18'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='expiration_date',
            field=models.DateField(default='2023-11-18'),
        ),
    ]
